camera-01:
  name: Real video 20221003
  source: demo_videos/20221003-102700.mp4
  loop: true
  max_fps: 0
  enabled: true

camera-02:
  name: ACC camera 07-52
  source: "demo_videos/ACC Export-2022-10-20 07.52.49.554 AM.avi"
  loop: true
  max_fps: 15
  enabled: true

camera-03:
  name: ACC camera 08-33
  source: "demo_videos/ACC Export-2022-10-20 08.33.57.228 AM.avi"
  loop: true
  max_fps: 15
  enabled: true

camera-04:
  name: Ly Thuong Kiet - Hang Bai
  source: "demo_videos/16h15.7.9.22.mp4"
  loop: true
  max_fps: 0
  enabled: true

# camera-04:
#   name: RTSP test
#   source: "rtsp://rtsp.rtsplink.com:8554/live/objects?token=b3fefef77fb6c2d2af2795a41087b390d5892d50d295bb17c1c5c70fcd152cb0"
#   loop: false
#   max_fps: 15
#   enabled: true
