camera-01:
  name: Real video 20221003
  source: demo_videos/20221003-102700.mp4
  loop: true
  max_fps: 0
  enabled: true

camera-02:
  name: ACC camera 07-52
  source: "demo_videos/ACC Export-2022-10-20 07.52.49.554 AM.avi"
  loop: true
  max_fps: 0
  enabled: true

camera-03:
  name: ACC camera 08-33
  source: "demo_videos/ACC Export-2022-10-20 08.33.57.228 AM.avi"
  loop: true
  max_fps: 0
  enabled: true

camera-04:
  name: ACC camera 07-52-xx
  source: "demo_videos/ACC Export-2022-10-20 07.52.49.554 AM.avi"
  loop: true
  max_fps: 0
  enabled: true

camera-05:
  name: ACC camera 08-33-xx
  source: "demo_videos/ACC Export-2022-10-20 08.33.57.228 AM.avi"
  loop: true
  max_fps: 0
  enabled: true